### ISSUE TITLE
Cannot find module 'wordwrap'

### ISSUE THREAD

**Issue by Aitorpm** [facebook/metro-bundler#79]
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
When I'm trying to build the project with "react-native run-android". Packager throws the following error when bundling:
Error: Cannot find module 'wordwrap'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/apple/Documents/Workspace/appUnifyme/node_modules/metro-bundler/src/lib/formatBanner.js:15:16)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

So, there is a require of the module wordwrap but this module wasn't install. To fix the bug I installed the module with the classic "npm install wordwrap".

**Comment by raarts** [comment]
+1

**Comment by BuffMcBigHuge** [comment]
`yarn install` solves this, or `npm install wordwrap -s`.

**Comment by lukewis** [comment]
This is caused by #130.
